AppName: Senana

Datapath:
  Root: "C:\\Users\\Uyen\\Documents\\nlp\\YNdata"
  Train: "train_price.csv"
  Validate: "valid_price.csv"
  Test: "test_price.csv"
  Raw: "C:\\Users\\Uyen\\Documents\\nlp\\YNdata\\PRICE_MAY_NOV_2019.csv"

